### ISSUE TITLE
Update npm package.

### ISSUE THREAD

**Issue by tijszwinkels** [strophe/strophejs#224]
The 'strophe' package on npm is stuck on 1.2.4, and hasn't been updated for 11 months:
https://www.npmjs.com/package/strophe

There is also strophe.js package, that is up-to-date:
https://www.npmjs.com/package/strophe.js

Why do we have these two packages? Can these be synchronised, or can the old one get a warning to tell people to update to the new one?

**Comment by jcbrand** [comment]
We'll have to ask @flosse about this, he's the owner of the first package (and I'm the owner of the 2nd one). I can't access/touch the first.

**Comment by flosse** [comment]
Does someone like to take the ownership?

**Comment by jcbrand** [comment]
I wonder what the right thing to do is here... I don't want to maintain two NPM repos. So ideally we would be able to merge the two (or delete @flosse's without disrupting existing deployments). This is probably something to ask NPM.

**Comment by tijszwinkels** [comment]
I'm not aware of any way of merging npm packages. Simply deleting ('unpublishing') the strophe package is a bad idea, as that would break things for anybody (including me) that is already using this package.

I think the best way would be to deprecate one of the packages. (https://docs.npmjs.com/cli/deprecate)
A deprecation message can be configured, telling users to use the other package-name instead. In that way, existing code won't break for anyone, but people would receive a warning message telling them to migratie for any future uses of the library.

@flosse: Would that be an acceptable solution?

**Comment by jcbrand** [comment]
Thanks for the info @tijszwinkels 

@flosse will you be willing to deprecate your strophe repo by writing a deprecation message for version 1.2.4? In the deprecation message you could then inform people that the strophe.js is up to date and should be used for newer versions.

**Comment by denschub** [comment]
In theory, couldn't you just publish an empty, deprecated package that has `strophe.js` as a dependency?

**Comment by flosse** [comment]
> @flosse will you be willing to deprecate your strophe repo by writing a deprecation message for version 1.2.4? 

done :)

**Comment by flosse** [comment]
> In theory, couldn't you just publish an empty, deprecated package that has `strophe.js` as a dependency?

Sure I could but it might be better to inform the user to switch to `strophe.js`!?

**Comment by denschub** [comment]
Totally, that's why I said the dummy package should be deprecated. But people sticking around on the old package would still get new sources. However, that's just an idea I had while reading this conversation. :)

**Comment by jcbrand** [comment]
Thanks @flosse. I think it's fine the way it is new.

Introducing a dependency on `strophe.js` in `strophe` would not really solve the issue AFAICT, since the dependency would have a different path, so paths would still be broken.
